# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
        - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
